version: "3.7"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=locar
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  app:
    build: .
    container_name: locar_api
    volumes:
      - .:/usr/app
    network_mode: host
    depends_on:
      - "postgres"

volumes:
  pgdata:
    driver: local
